site_name: DoDomuDojade - Dokumentacja
docs_dir: resources/docs
site_dir: build
site_url: https://sloths4.github.io/DoDomuDojade/
use_directory_urls: true

nav:
  - Home: index.md
  - Architektura: architecture.md
  - Przyk≈Çady: examples/index.md
  - Warstwy:
      - Aplikacji: layers/application.md
      - Domeny: layers/domain.md
      - Infrastruktury: layers/infrastructure.md

theme:
  name: material
  locale: en
  palette:
    - scheme: light
      primary: teal
    - scheme: dark
      primary: teal
  highlightjs: false
  features:
    - content.code.copy
    - navigation.top

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true

  - pymdownx.superfences

  - tables

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
