version: '3.9'

services:
  php-fpm:
    build: ..
    ports: ["9000:9000"]
    environment:
      - REDIS_HOST=redis
    depends_on: [redis, db]
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports: ["8000:80"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: [php-fpm]

  redis:
    image: redis:latest
    ports: ["6379:6379"]

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME:dodomudojade}
      - POSTGRES_USER=${DB_USERNAME:postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:}
    ports: ["5432:5432"]

  cron:
    build: .
    command: bash /app/docker/cron.sh
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    depends_on: [ redis, db, php-fpm ]
    volumes:
      - .:/app
      - ./logs:/var/log
