name: Build Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          stability: nightly
          extensions: >
            json,
            pdo,
            mbstring,
            simplexml,
            libxml,
            readline,
            dom,
            tokenizer,
            xml,
            xmlwriter,
            ctype,
            iconv,
            filter

      - name: Install PHP deps
        run: composer install --prefer-dist

      - name: Generate API docs
        run: vendor/bin/phpdoc run

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
